on: [push]

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure CLI script file
      uses: azure/cli@v2
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage blob sync -c "container2" --account-name "yangshensa98i1" --source "test1" --account-key ${{ secrets.ConnectionString }} 
