on: [push]

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install azcopy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        # when ubuntu-latest changes this needs updating from 22.04
        wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y azcopy
        rm -f packages-microsoft-prod.deb
        pwd
        sudo find / -name "azcopy"
        azcopy -v
        
        
