on: [push]

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install azcopy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        # when ubuntu-latest changes this needs updating from 22.04
        wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y azcopy
        rm -f packages-microsoft-prod.deb
        pwd
        sudo find / -name "azcopy"
        azcopy -v
    
    - name: Copy file to Azure Blob Storage
      env:
        AZURE_STORAGE_ACCOUNT: yangshensa98i1
        AZURE_CONTAINER_NAME: container2
        AZCOPY_AUTO_LOGIN_TYPE: AZCLI
        AZCOPY_TENANT_ID: ${{ secrets.AZURE_CREDENTIALS.tenantId }}
      run: |
        azcopy sync "." "https://$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$AZURE_CONTAINER_NAME/"
        
        
