on: [push]

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v4
   
    - name: Copy file to Azure Blob Storage
      env:
        AZURE_STORAGE_ACCOUNT: yangshensa98i1
        AZURE_CONTAINER_NAME: container2
        AZCOPY_AUTO_LOGIN_TYPE: AZCLI
        AZCOPY_TENANT_ID: 16b3c013-d300-468d-ac64-7eda0820b6d3
      run: |
        azcopy sync "test1" "https://$AZURE_STORAGE_ACCOUNT.blob.core.windows.net/$AZURE_CONTAINER_NAME/"
        
        
