name: Azure Blob Storage Upload

on:
  push:
    branches:
      - main
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: test1
          container_name: container1
          connection_string: ${{ secrets.ConnectionString }}
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'

